export const FETCH_EVERYTHING = "FETCH_EVERYTHING";
export const FETCH_HEADLINES = "FETCH_HEADLINES";
export const EVERYTHING_LOADING = "EVERYTHING_LOADING";
export const HEADLINES_LOADING = "HEADLINES_LOADING";
